[package]
name = "raining_glyph"
version = "0.1.0"
edition = "2021"

[dependencies]
anathema = { git = "https://github.com/togglebyte/anathema/", branch = "dev" }
colorsys = "0.6.7"
rand = "0.9.0-alpha.2"
